export enum InjuryBodyRegion {
  HEAD = 'HEAD',
  NECK = 'NECK',
  BACK = 'BACK',
  CHEST = 'CHEST',
  ABDOMEN = 'ABDOMEN',
  PELVIS = 'PELVIS',
  LEFT_FRONT_LEG = 'LEFT_FRONT_LEG',
  RIGHT_FRONT_LEG = 'RIGHT_FRONT_LEG',
  LEFT_HIND_LEG = 'LEFT_HIND_LEG',
  RIGHT_HIND_LEG = 'RIGHT_HIND_LEG',
  OTHER = 'OTHER',
}

export enum InjuryType {
  FRACTURE = 'FRACTURE',
  SPRAIN = 'SPRAIN',
  STRAIN = 'STRAIN',
  WOUND = 'WOUND',
  LACERATION = 'LACERATION',
  INFLAMMATION = 'INFLAMMATION',
  CONTUSION = 'CONTUSION',
  INFECTION = 'INFECTION',
  OTHER = 'OTHER',
}

export enum RecoveryStatus {
  ACUTE = 'ACUTE',
  RECOVERING = 'RECOVERING',
  HEALED = 'HEALED',
}
