export enum SessionParticipantStatus {
  PLANNED = 'PLANNED',
  PRESENT = 'PRESENT',
  READY = 'READY',
  ONGOING = 'ONGOING',
  COMPLETED = 'COMPLETED',
  ABSENT = 'ABSENT',
  SKIPPED = 'SKIPPED',
  INELIGIBLE = 'INELIGIBLE',
  CANCELLED_BY_LOCK = 'CANCELLED_BY_LOCK',
  CANCELLED = 'CANCELLED',
}
