/**
 * The reasons a horse is not fully eligible for training or racing
 */
export enum EligibilityReason {
  REFERENCE_HORSE = 'REFERENCE_HORSE',
  LIFECYCLE_NOT_ACTIVE = 'LIFECYCLE_NOT_ACTIVE',
  HEALTH_UNDER_OBSERVATION = 'HEALTH_UNDER_OBSERVATION',
  HEALTH_INJURED = 'HEALTH_INJURED',
  HEALTH_QUARANTINED = 'HEALTH_QUARANTINED',
  ACTIVE_TRAINING_LOCK = 'ACTIVE_TRAINING_LOCK',
}
