/**
 * Các lý do ngựa không đủ điều kiện tập hoặc đua
 */
export enum EligibilityReason {
  PROFILE_DELETED = 'PROFILE_DELETED',
  LIFECYCLE_RETIRED = 'LIFECYCLE_RETIRED',
  LIFECYCLE_TRANSFERRED = 'LIFECYCLE_TRANSFERRED',
  LIFECYCLE_DECEASED = 'LIFECYCLE_DECEASED',
  HEALTH_UNDER_OBSERVATION = 'HEALTH_UNDER_OBSERVATION',
  HEALTH_INJURED = 'HEALTH_INJURED',
  HEALTH_QUARANTINED = 'HEALTH_QUARANTINED',
  ACTIVE_TRAINING_LOCK = 'ACTIVE_TRAINING_LOCK',
}
